services:

  worker:
    build: .
    container_name: disttask_worker
    command: watchfiles "python -m app.worker.runner" app
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - disttask_network

  producer:
    build: .
    command: watchfiles "python -m app.queue.producer" app
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - disttask_network

  redis:
    image: redis:7-alpine
    container_name: disttask_redis
    volumes:
      - redis_data:/data
    networks:
      - disttask_network

  postgres:
    image: postgres:16
    container_name: disttask_postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - disttask_network

volumes:
  redis_data:
  postgres_data:

networks:
  disttask_network:
    driver: bridge